### ISSUE TITLE
tbl_sirup (jenis_pengadaan) actual values

### ISSUE THREAD

**Issue by mireille-raad** [OC-Bandung/OCDS-publication#5]
Hello @bdgcoder  :) 

for tbl_sirup, the jenis_pengadaan have values of 1,2,3,4 .... it is probably linked to the table tbl_jenis (with jenisID and nama)

Can you share what the 1,2,3 and 4 mean? (as they are in the database, no translation)

Thank you!

**Comment by bdgcoder** [comment]
Because tbl_sirup from sirup API, and LKPP doesn't create relation for the data. This is Complete Legend from tbl_sirup from LKPP.

**JENIS_PENGADAAN**
1;"Barang"
2;"Pekerjaan Konstruksi"
3;"Jasa Konsultansi"
4;"Jasa Lainnya"

**METODE PENGADAAN**
1;"Lelang Umum"
2;"Lelang Sederhana"
3;"Lelang Terbatas"
4;"Seleksi Umum"
5;"Seleksi Sederhana"
6;"Pemilihan Langsung"
7;"Penunjukan Langsung"
8;"Pengadaan Langsung"
9;"e-Purchasing"
10;"Sayembara"
11;"Kontes"
12;"Lelang Cepat"

**Comment by mireille-raad** [comment]
Excellent!!! many thanks for the data!
